"""
Django settings for classroom_tasks project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
# Configuración rápida para desarrollo
SECRET_KEY = 'django-insecure-@5)^6dr&6h&%m*avokjr)+*&q*_#(!*3bb@+701(y45$ka$!98' # Clave secreta
DEBUG = True        # Modo debug activado
ALLOWED_HOSTS = []  # Hosts permitidos


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tasks',        # Registramos nuestras apps
    'accounts',     # App de usuarios
]

# Middleware del proyecto
MIDDLEWARE = [ 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Archivo principal de rutas
ROOT_URLCONF = 'classroom_tasks.urls'  

# Configuración de plantillas
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # Carpeta global de plantillas
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',   # Añade request al contexto
                'django.contrib.auth.context_processors.auth',  # Añade user al contexto
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'classroom_tasks.wsgi.application' # Configuración WSGI


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # Motor PostgreSQL
        'NAME': 'dwes_practica_ut04',               # nombre de la base de datos
        'USER': 'isard',                            # usuario de PostgreSQL
        'PASSWORD': 'pirineus',                     # contraseña
        'HOST': '127.0.0.1',                        # servidor de la BD
        'PORT': '5433',                             # puerto por defecto de PostgreSQL
    }
}


# Validadores de contraseña
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},    # Similaridad   
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator' },             # Longitud mínima
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},             # Contraseñas comunes
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator' },           # Solo números  
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/ 

LANGUAGE_CODE = 'es-es'         # Cambiado a español
TIME_ZONE = 'Europe/Madrid'     # Ajustado a tu zona horaria
USE_I18N = True                 # Internacionalización
USE_TZ = True                   # Uso de zonas horarias


# Archivos estáticos (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/ 

STATIC_URL = 'static/'  # URL de estáticos
STATICFILES_DIRS = [BASE_DIR / 'classroom_tasks' / 'static']    # Carpeta de estáticos

 # Tipo de clave primaria por defecto
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de login
LOGIN_URL = '/accounts/login/'            # Redirige al login del admin si no está autenticado
LOGIN_REDIRECT_URL = '/tasks/mine/'       # Tras login, redirige al listado de tareas
LOGOUT_REDIRECT_URL = '/accounts/login/'  # Tras logout, redirige a la raíz
AUTH_USER_MODEL = 'accounts.User'
