# Generated by Django 5.2.6 on 2025-12-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_task_delivery_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADA', 'Entregada'), ('VALIDADA', 'Validada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual'), ('GRUPAL', 'Grupal')], max_length=20, verbose_name='Tipo'),
        ),
    ]
