# Generated by Django 5.2.6 on 2025-12-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Alumno'), ('teacher', 'Profesor')], default='student', max_length=10),
        ),
    ]
